# Generated by Django 5.0.2 on 2024-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=70)),
                ('introduccion', models.TextField(max_length=200, null=True)),
                ('contenido', models.TextField(max_length=3000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='App_Core')),
                ('video', models.URLField(null=True)),
                ('podcast', models.URLField(null=True)),
                ('autor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
