# Generated by Django 5.0.2 on 2024-03-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduccion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='podcast',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
