# Generated by Django 5.0.2 on 2024-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0005_alter_post_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
