# Generated by Django 5.0.2 on 2024-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='art_relacionado',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
