# Generated by Django 5.0.2 on 2024-03-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0008_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='art_relacionado',
            field=models.CharField(blank=True, default='{{post.titulo}}', editable=False, max_length=70, null=True),
        ),
    ]
