# Generated by Django 5.0.2 on 2024-03-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0009_alter_comentario_art_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='art_relacionado',
            field=models.CharField(blank=True, editable=False, max_length=70, null=True),
        ),
    ]
