# Generated by Django 5.0.2 on 2024-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0010_alter_comentario_art_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
    ]
