# Generated by Django 5.0.2 on 2024-04-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0012_alter_post_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='podcast',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
