# Generated by Django 5.0.2 on 2024-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Core', '0013_alter_post_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='podcast',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
